#!/usr/bin/csh

set figures={NSSMLP,preuve_cvx_appui,double_cone,barycentre_dual,etanch,hexa_grille_tube2,grille_h,edt_breu,preuve,preuve_bis,preuve2,coupuresbis,preuve_2bis,fig2,preuve_cache}

#cd fig/



foreach fig ($figures)

		#if (-M $fig.fig > -M $fig.ps) then 
		echo Compile de $fig
		echo creation de $fig.pstex
		fig2dev -L pstex  $fig.fig  $fig.pstex
		echo creation de $fig.tex_1
		fig2dev -L pstex_t -p $fig.pstex $fig.fig >! $fig.tex_1
		

		echo creation de $fig.tex
		echo "%%%%" >! $fig.tex
		echo "\documentclass[10pt]{report}" >>  $fig.tex
		echo "\usepackage{graphicx,color,epsfig,psfig,subfigure}" >>  $fig.tex
		echo "\usepackage{amsmath,amsfonts,amssymb}" >>  $fig.tex
		echo "\usepackage{bm}" >>  $fig.tex
		echo "\pagestyle{empty}" >>  $fig.tex
		echo '\begin{document}' >>  $fig.tex
		cat $fig.tex_1 >>  $fig.tex
		echo "\end{document}" >>  $fig.tex
		

		echo compilation  de $fig.tex
		latex $fig.tex 
#> /dev/null
		
		echo création du postscript
		dvips $fig.dvi -o -E 
		#cp $fig.ps .. 
		#cd ..
		##else 
		##echo $fig up to date
		#endif
end

